# Generated by Django 4.1.1 on 2022-10-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_alter_board_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
