repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.270
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
# Using flake8 for TC rules only, because rules TC1/TC2 are not yet implemented in ruff
# (only rules TC001 - TC005 are available).
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: ['--select=TC']
      entry: pflake8
      additional_dependencies:
        - pyproject-flake8
        - flake8-type-checking
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.10
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    - id: mypy
      additional_dependencies:
        - django-stubs
        - djangorestframework-stubs
        - psycopg2
        - pytest
        - pytest_factoryboy
        - django-environ
        - djangorestframework
        - drf_yasg
        - django-filter
        - django-filter-stubs
        - celery
        - celery-stubs
        - shortuuid
        - pytest_mock
      args: [--strict]
      exclude: '^env/|migrations|.git|.mypy_cache|pytest_cache'
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: docker-compose run --rm -T django pytest --cov-fail-under=95
      language: system
      pass_filenames: false
      always_run: true
      stages: ["push", "merge-commit", "manual"]