repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--line-length", "79"]
- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
    - id: black
      args: [ --diff, --check ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.981
  hooks:
    - id: mypy
      exclude: ^tests/
      args: [ --strict ]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
-   repo: https://github.com/guilatrova/tryceratops
    rev: v1.1.0
    hooks:
      - id: tryceratops