version: '3.10'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: "base"
    command: gunicorn boards_of_django.wsgi:application --workers 2 --bind 0.0.0.0:8000 --reload
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    volumes:
      - ".:/usr/src/app"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - django
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - "./static:/usr/src/static"
      - "./media:/usr/src/media"
    depends_on:
      django:
        condition: service_started
    networks:
      - django
  redis:
    image: redis:alpine
    networks:
      - django
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: celery -A tasks worker -l info
    volumes:
      - ".:/usr/src/app"
    env_file:
     - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      django:
        condition: service_started
    networks:
      - django

volumes:
  postgres_data:
networks:
  django: