# Generated by Django 4.1.1 on 2022-10-19 06:25

import django.core.validators
from django.db import migrations, models

import boards.models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    boards.models._validate_contains_allowed_characters,
                ],
            ),
        ),
    ]
